#define PLEXORA_DOWN -1
#define PLEXORA_CKEYPOLL_FAILED 0
#define PLEXORA_CKEYPOLL_NOTLINKED 1
#define PLEXORA_CKEYPOLL_RECORDNOTVALID 2
#define PLEXORA_CKEYPOLL_LINKED 3
#define PLEXORA_CKEYPOLL_LINKED_ABSENT 4
#define PLEXORA_CKEYPOLL_LINKED_BANNED 5
#define PLEXORA_CKEYPOLL_LINKED_DELETED 6
